---
title: "Exercise 1 - Tashfeen Ahmed - 261145667"
output: pdf_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, results='hide'}
# Load the necessary libraries
library(dplyr)
#install.packages("tidygraph")
#install.packages("tibble")
library(tibble)
library(tidygraph)
library(igraph)
#install.packages("ggraph")
library(ggraph)
library(purrr)
library(tidyr)
library(stringr)
library(readr)
library(ggrepel)
```


```{r}
Connections <- read_csv("D:\\Google Drive\\McGill\\Winter Semester\\W2\\Talent-Analytics-Assignments\\Part 2\\Exercise 1\\Connections.csv", skip = 3)
```



```{r}
Connections <- Connections[!is.na(Connections$Company), ]
# Group by 'Company' and count the number of contacts per company
company_counts <- Connections %>%
  group_by(Company) %>%
  summarise(Count = n())

# Calculate the total count of contacts
total_count <- nrow(Connections)

# Print the count of contacts by company and the total count
print(paste("Total count of contacts:", total_count))

```


```{r}
# Viewing the dataset in descending order
company_counts <- arrange(company_counts, desc(Count))
head(company_counts,10)

```


```{r}

# Keep only the first name and the first letter of the last name as a label for the nodes
Connections <- Connections %>%
  mutate(label = paste(`First Name`, substr(`Last Name`, 1, 1)))
Connections <- Connections %>%
  mutate(title = paste(`First Name`, substr(`Last Name`, 1, 1)))

# Create edges dataframe
edges <- Connections %>%
  select(label, Company) %>%
  distinct() %>%
  group_by(Company) %>%
  filter(n() > 1) %>%
  summarise(pair = list(combn(label, 2, simplify = FALSE))) %>%
  unnest(pair) %>%
  mutate(from = map_chr(pair, 1), to = map_chr(pair, 2)) %>%
  select(from, to, Company)  # Add Company column to the edges dataframe

# Create the graph
graph_connections <- as_tbl_graph(edges)

# Add title, label, and Company attributes to the nodes
graph_connections <- graph_connections %>%
  activate(nodes) %>%
  mutate(
    title = str_to_title(name),
    label = str_replace_all(title, " ", "\n"),
  )




```


```{r}
graph_connections
```



```{r fig.width=20, fig.height=15}
# Visualize the graph
g <- ggraph(graph_connections, layout = "kk") + 
  geom_edge_link(aes(edge_alpha = 0.1, color = Company), size = 0.5) +  # Slightly thicker edges
  geom_node_text(aes(label = label), size = 4) +  # Larger text
  scale_color_brewer(palette = "Dark2") +  # Different palette
  theme_void() + 
  theme(legend.position = "none", plot.background = element_rect(fill = "white")) + 
  geom_node_point(color = "blue", size = 3)

# Print the graph
print(g)

ggsave("graph_connections.png", plot = g, width = 20, height = 15, bg = "white")
```

Note: Same color edges means same Company




























